# Generated by Django 5.1.6 on 2025-03-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imageurl',
            field=models.CharField(default='default.jpg', max_length=120),
            preserve_default=False,
        ),
    ]
