# Generated by Django 5.1.6 on 2025-03-03 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_noticia_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='foto',
        ),
    ]
