# Generated by Django 5.1.6 on 2025-03-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_remove_noticia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
    ]
